name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r stockalert/requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest
        # Test that modules can be imported without errors
        python -c "from stockalert.utils.env_loader import load_environment; print('Environment loader imported successfully')"
